### PR TITLE
Dataset 2412 reading

### PR DESCRIPTION
**Pull request by mglesser**
Dear contributors,
I've updated pyuff.py to handle the reading of dataset 2412. It partially solves issue #34. I'll try to implement the writing function as soon as possible. 

Being not familiar with the test framework that is used in the project, I'm afraid my test function is a little bit naive.

### CODE REVIEW

**Comment by jankoslavic** [comment]
Dear @mglesser ! looks very good. please check my corrections.

**Comment by mglesser** [comment]
@jankoslavic Thanks for the review and corrections. I've just made a very small change in the test for homogeneity.

**Comment by jankoslavic** [comment]
Thanks @mglesser Maybe someday in the future: would take the effort to also prepare the methods for writing of 2412?

**Comment by mglesser** [comment]
@jankoslavic sure, I was a bit in a hurry to get the reading function done. But I'll prepare the method for writing also.

**Pull request merged**
