### PR TITLE
ToDo ascii 58

### PR DESCRIPTION
**Pull request by K-Mohr**
# TODO: This is not a good implementation -- sometimes there is no space between values and we get '2.99110e-02-10.00000e-05'. The string should be split by number of characters!24

Have made character implementation that should resolve the issue it has been tested succesfully on no_spacing_uff58_ascii.uff in data folder and no_spacing2_uff58_ascii.uff

### CODE REVIEW

**Comment by jankoslavic** [comment]
Dear @K-Mohr thank you for your contribution. All current test should pass. Please check also the performance of the current implementation vs the proposed!

**Comment by K-Mohr** [comment]
image

Hi jankoslavic, It is my first time coding. It should pass the test

**Comment by jankoslavic** [comment]
Dear @K-Mohr this looks very good. Would you please be so kind and also check the performance? I would not like to slow down the reading...

**Comment by jankoslavic** [comment]
Dear @K-Mohr I have checked the performance and it looks fine; it is similar as before; however, you should not change the test files; all current files should work without problems. Please remove also the cached files (this should not go on github)

**Comment by K-Mohr** [comment]
Dear @jankoslavic I wasn't sure how to test the performance other than with the pytest. Have removed the data files as requested.

**Comment by jankoslavic** [comment]
Thanks, can you please put back also the "measurement.uff"?

**Comment by jankoslavic** [comment]
@K-Mohr  can you please provide me with the file that you are having problems reading with the current version of pyuff? (your solution looks somehow complicated)

**Comment by K-Mohr** [comment]
Should I add them in the comment or how do you want them?

**Comment by jankoslavic** [comment]
Please upload the file here:
https://gist.github.com/ and publish the link here

**Comment by K-Mohr** [comment]
I am getting a 405 not allowed error?

**Comment by K-Mohr** [comment]
Two problematic UFF58 files
[https://gist.github.com/K-Mohr/07b9a5b2f60835958bade40da665729e](url)
[https://gist.github.com/K-Mohr/40bad525397898e3ef1b012fbf91fd57](url)

**Comment by jankoslavic** [comment]
dear @K-Mohr I rewrote the parser for 58 type. Now the record 12 should be read with regards to all the variety written here: http://sdrl.uc.edu/sdrl/referenceinfo/universalfileformats/file-format-storehouse/universal-dataset-number-58

(the case 6x13 you programmed is just one of 8 options)

**Pull request closed without merging**
