### PR TITLE
fixed dataset 58 and 58b, added time-series example

### PR DESCRIPTION
**Pull request by kb-**
I fixed the following:
-Non ASCII copyright comment caused error (the file wouldn't run with the accents)
-Dataset 58, Record 7 fields 4,5,6 should be 3E13.5 according to specification
-58b: binary data was unreadable in other software

### CODE REVIEW

**Comment by kb-** [comment]
1. `import pyuff` gives me the following error with Python 2.7. ok with 3.6

>   File "pyuff.py", line 1
>     # Copyright (C) 2014-2017 Primož Čermelj, Matjaž Mršnik, Miha Pirnat, Janko Slavič, Blaž Starc (in alphabetic order)
>                                                                                                                         ^
> SyntaxError: Non-ASCII character '\xc5' in file pyuff.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

3. I was missing both a binary and an example to write time series.
4. 58b produced by your code fails to be read properly in commercial software (nCode). I can try different softwares if necessary. The proposed modification is working for np.single datatype only.
[test58b_double_original.uff](https://mega.nz/#!Xg4FTAiK!hvAl15nNaFDbSXeIcETO8Vdn717KCQaT9a3WcC3lA2c) : your code, passed np.double datatype
image


[test58b_single_original.uff](https://mega.nz/#!rogxHSgQ!jt7nmZ6sKjB31QfXpvOvLYlVFX5TNLcL-XDvKFnTeOA) : your code, passed np.singledatatype
image


[test58b_double_modified.uff](https://mega.nz/#!CxplUKwS!4weaFvFg6K4l1-GGSirMP6H2oeg4ct9EzPbXq_EMgF4) : modified code, np.double datatype
image


[test58b_single_modified.uff](https://mega.nz/#!Dhg1WQDL!NEvND7HBYUQIoYQV-zGdATTR_-LKUoCzkcnhM1j5bp8) : OK, modified code, passed np.singledatatype
image

**Comment by jankoslavic** [comment]
Thanks for the feedback. 

1. is related to the closed issue: https://github.com/openmodal/pyuff/issues/1

4. If I understand correctly, the provided examples are written with pyuff and read inside nCode. Is it possible to get nCode exported 58b? I could have this file to prepare reading/writing nCode round test.

**Comment by kb-** [comment]
1. Ok, it would be nice to make it obvious either by writing it in the module description and README or by throwing an error message. Python 2 or 3 compatibility is often a frustration, especially when we don't know why a module isn't working. Your module seems to work fine on Python 2 after removing the accents tho.

2. nCode can't generate this type of file unfortunately, only import. I'll get back to you when I can find this type of files from another source. Probably next week.

**Comment by jankoslavic** [comment]
1. if the non ascii characters in the comments are a problem, I have added file encoding to the files. Is it working for you now?
2. this would be great!

**Comment by jankoslavic** [comment]
PS: the last commit includes 13.5e formating (in all fields, not only the ones you pointed out; I do not remember why we were using 13.4e; I hope it will not break other people's code - all test are working fine) Can you please double check your files on this?

**Pull request closed without merging**
